name: Deploy to Production

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_KEY" > ~/.ssh/production.key
                  chmod 600 ~/.ssh/production.key
                  cat >>~/.ssh/config <<END
                  Host production
                      HostName $SSH_HOST
                      User $SSH_USER
                      IdentityFile ~/.ssh/production.key
                      StrictHostKeyChecking no
                  END
              env:
                  SSH_USER: ${{ secrets.SSH_USER }}
                  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SSH_HOST: ${{ secrets.SSH_HOST }}

            - name: Deploy to production
              run: ssh production 'bash -s' < deploy.sh
